export class Element {
    constructor(
        public id: number,
        public user_id: number,
        public name: string,
        public description: string,
        public unit_amount:number,
        public unit_measurement:string,
        public unit_costprice:number,
        public unit_profitpercentage:number,
        public unit_price:number,

        public surface_multiple:boolean,
        public surface_multiple_amount:number,
        public surface_height:number,
        public surface_width:number,
        public surface_layout:string,
        public surface_article_height:number,
        public surface_article_width:number,
        public surface_article_layout:string,
        public surface_itens:number,
        public surface_total_surfaces: number,
        public surface_whole:string,
        public surface_surcharge_item: number,
        public surface_individual_cost: number,
        public surface_costprice:number,
        public surface_profitpercentage:number,
        public surface_price:number,

        public coil_width:number,
        public coil_article_height:number,
        public coil_article_width:number,
        public coil_article_layout:string,
        public coil_articles_amount:number,
        public coil_total_measure: number,
        public coil_surcharge_item: number,
        public coil_measured_cost: number,
        public coil_costprice:number,
        public coil_profitpercentage:number,
        public coil_price:number,
    ) { }
}